#!/bin/bash

case $1 in
   config)

	echo "graph_category LiquidFeedback"
	echo "graph_title delegation"
	echo "graph_vlabel count"

	echo "trustee.label trustee"
	echo "truster.label truster"
	echo "indelegation.label avg incoming delegations"
	echo "outdelegation.label avg outgoing delegtions"

        exit 0;;
esac

trustees=$(psql liquid_feedback_pp -At -c "SELECT COUNT (DISTINCT trustee_id) FROM delegation;")
trusters=$(psql liquid_feedback_pp -At -c "SELECT COUNT (DISTINCT truster_id) FROM delegation;")

echo "trustee.value $trustees"
echo "truster.value $trusters"

delegation_count=$(psql liquid_feedback_pp -At -c "SELECT COUNT (DISTINCT id) FROM delegation;")

indelegations=$(echo "scale=2; $delegation_count/$trustees" | bc)
outdelegations=$(echo "scale=2; $delegation_count/$trusters" | bc)

echo "indelegation.value $indelegations"
echo "outdelegation.value $outdelegations"

