#!/bin/sh

case $1 in
   config)

	echo "graph_category LiquidFeedback"
	echo "graph_title issues in areas"
	echo "graph_vlabel number of issues per area"
        
	count=$(psql liquid_feedback_pp -At -c "SELECT COUNT (id) FROM area;")

	for (( i=1; i<=$count; i++ ))
	do  
        	echo ${i}.label $(psql liquid_feedback_pp -At -c "Select name from area where id='$i';")
	done

        exit 0
        ;; 
esac

count=$(psql liquid_feedback_pp -At -c "SELECT COUNT (id) FROM area;")

for (( i=1; i<=$count; i++ ))
do
	echo -n "$i.value "; psql liquid_feedback_pp -At -c "select count (id) from issue where area_id='$i';"
done

